version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: tatak-pay-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tatak
      POSTGRES_PASSWORD: Tatak@Pay
      POSTGRES_DB: tatak-pay-db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
